### ISSUE TITLE
如何使用自动雪碧图功能呢？

### ISSUE THREAD

**Issue by vb3064** [QMUI/QMUIDemo_Web#1]
在\UI_dev\project\images\中新建一个目录，里面放置png图片，编译后，不会自动生成合并的图片啊？这个功能应该如何使用呢？有没有具体一点的案例吗？

**Comment by kayo5994** [comment]
新建目录后 Sass 中需要写一些调用代码，才会生成雪碧图，具体可以参考[扩展组件](http://qmuiteam.com/web/page/widget.html#qui_widget_autoSprite)，里面有完整的文字说明以及代码。
